"""Isolated test and diagnostic router for FLUX.2 Klein 4B / Nano Banana image generation."""
from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, File, Form, HTTPException, UploadFile, status
import httpx

from app.services.image_generation.factory import get_image_provider
from app.services.upload_manager import UploadManager

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/image-generation", tags=["image-generation"])


@router.get("/health")
async def provider_health(provider: str | None = None) -> dict[str, Any]:
    """Check health and credential status of configured or requested image provider."""
    try:
        instance = get_image_provider(provider_override=provider)
        healthy = await instance.health_check()
        return {
            "status": "healthy" if healthy else "degraded",
            "provider": getattr(instance, "model_name", "unknown"),
            "class": instance.__class__.__name__,
        }
    except Exception as exc:  # noqa: BLE001
        return {
            "status": "unhealthy",
            "error": str(exc),
        }


@router.post("/test")
async def test_image_generation(
    prompt: str = Form(..., description="Prompt instruction for generation or edit"),
    image: UploadFile | None = File(None, description="Optional input garment image to edit/reconstruct"),
    image_url: str | None = Form(None, description="Optional public URL to input image"),
    provider: str | None = Form(None, description="Provider override: 'runpod', 'gemini', or 'mock'"),
    strength: float = Form(0.45, description="Denoising strength (0.35 - 0.65)"),
    aspect_ratio: str = Form("1:1", description="Aspect ratio for text-to-image"),
) -> dict[str, Any]:
    """Isolated test endpoint to evaluate FLUX.2 Klein 4B without modifying closet items."""
    try:
        provider_instance = get_image_provider(provider_override=provider)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Image generation provider error: {exc}",
        ) from exc

    input_bytes: bytes | None = None
    if image is not None:
        input_bytes = await image.read()
    elif image_url:
        try:
            async with httpx.AsyncClient(timeout=15.0) as client:
                res = await client.get(image_url)
                if res.status_code == 200:
                    input_bytes = res.content
                else:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Failed to fetch image from URL: HTTP {res.status_code}",
                    )
        except Exception as exc:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Failed to load image from URL: {exc}",
            ) from exc

    try:
        if input_bytes:
            result = await provider_instance.edit_image(
                image_bytes=input_bytes,
                prompt=prompt,
                strength=strength,
            )
        else:
            result = await provider_instance.generate_image(
                prompt=prompt,
                aspect_ratio=aspect_ratio,
            )

        # Upload generated bytes via UploadManager to maintain storage contract
        uploaded_url = await UploadManager.upload_bytes(
            file_bytes=result.image_bytes,
            mime_type=result.mime_type,
            extension="png",
        )

        return {
            "status": "success",
            "image_url": uploaded_url,
            "provider": result.provider,
            "model_name": result.model_name,
            "latency_ms": result.latency_ms,
            "metadata": result.metadata,
        }

    except Exception as exc:
        logger.exception("Image generation test failed: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Image generation test failed: {exc}",
        ) from exc
