#!/usr/bin/env python3
"""Generates the DressApp Eyes Gemma-4 E4B Colab Fine-Tuning Notebook with Tri-Dataset Training."""
import json
from pathlib import Path


def create_notebook():
    nb = {
        "nbformat": 4,
        "nbformat_minor": 0,
        "metadata": {
            "colab": {
                "name": "dressapp_eyes_gemma4_finetuning.ipynb",
                "provenance": [],
                "gpuType": "T4",
            },
            "kernelspec": {
                "name": "python3",
                "display_name": "Python 3",
            },
            "language_info": {
                "name": "python",
            },
            "accelerator": "GPU",
        },
        "cells": [],
    }

    def add_markdown(source_lines):
        nb["cells"].append({
            "cell_type": "markdown",
            "metadata": {},
            "source": [line + "\n" for line in source_lines],
        })

    def add_code(source_lines):
        nb["cells"].append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [line + "\n" for line in source_lines],
        })

    # Cell 1: Header Markdown
    add_markdown([
        "# 👗 DressApp Eyes (Gemma-4 E4B) Multimodal Fine-Tuning & Quantization Pipeline",
        "",
        "This notebook provides the complete end-to-end pipeline to fine-tune **DressApp Eyes** (`google/gemma-4-e4b-it`) across all fashion workflows using a **Tri-Dataset Hybrid Blend** from Hugging Face:",
        "1. **`ashraq/fashion-product-images-small`**: Clean isolated studio product cutouts for exact taxonomy grounding (Tops, Bottoms, Footwear, Accessories, Outerwear/Dresses).",
        "2. **`Marqo/deepfashion-multimodal`**: High-resolution garments with detailed descriptions for complex patterns (camo, plaid, floral), rich fabric materials (silk, linen, denim, wool), and fluent captions.",
        "3. **`ArtmeScienceLab/Garments2Look`**: 80,000 multi-garment to complete look pairs for full-body outfit coordination (mandatory top+bottom OR dress + footwear) and anatomical ordering.",
        "",
        "### Workflow Steps:",
        "1. **Environment Setup & llama.cpp Build**: Install PyTorch, Transformers, PEFT, BitsAndBytes, and compile `llama.cpp` tools (`convert_hf_to_gguf.py` & `llama-quantize`).",
        "2. **Import Assets from VPS**: Connect to the Hetzner VPS (`178.105.144.142`) via SCP to download `mmproj-BF16.gguf` and baseline files.",
        "3. **Tri-Dataset Ingestion & ETL**: Stream and format all three datasets directly into DressApp's canonical JSON schemas (`<garmentVision>`, `<Scheduled Outfit>`, `<Stylist Chat>`).",
        "4. **QLoRA Fine-Tuning**: 4-bit quantized SFT training targeting attention and MLP projections while preserving native vision embeddings.",
        "5. **Quantize to GGUF**: Merge PEFT LoRA into base weights, export intermediate F16 GGUF, and quantize to `Q3_K_M` (~2.85 GB) and `Q4_K_M`.",
        "6. **Evaluation & Smoke Tests**: Test attribute extraction, unique 2-4 word titles, 100% color/material sums, 3-tier gender hierarchy, and outfit coordination.",
        "7. **Push to VPS & Verify**: Securely upload `gemma-4-E4B-it-Q3_K_M.gguf` to `/srv/AI-Stylist/eyes_gguf/` and restart `dressapp-eyes`.",
    ])

    # Cell 2: Dependencies & Setup
    add_markdown([
        "## 🛠️ Step 1: Environment Setup & Tooling",
        "Install deep learning dependencies, Hugging Face streaming libraries, and build `llama.cpp` conversion and quantization tools.",
    ])
    add_code([
        "# Check GPU availability",
        "!nvidia-smi",
        "",
        "# Install Hugging Face, PEFT, BitsAndBytes, and Accelerate with compatible numpy & pandas",
        "!pip install -q -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121",
        "!pip install -q -U 'numpy>=2.1.0' 'pandas>=2.2.3' pyarrow",
        "!pip install -q -U transformers datasets peft bitsandbytes accelerate pillow paramiko scp",
        "",
        "# Clone and build llama.cpp for GGUF conversion & quantization utilities",
        "import os, sys",
        "if not os.path.exists('llama.cpp'):",
        "    !git clone https://github.com/ggerganov/llama.cpp.git",
        "    !cmake -B llama.cpp/build -S llama.cpp -DGGML_CUDA=OFF",
        "    !cmake --build llama.cpp/build --config Release -j$(nproc) --target llama-quantize",
        "    !pip install -q -r llama.cpp/requirements/requirements-convert_hf_to_gguf.txt",
        "",
        "print('✅ Dependencies installed and llama.cpp tools compiled!')",
        "print('⚠️ If you ever see \"ValueError: numpy.dtype size changed\", click: Runtime -> Restart session, then run from Step 3.')",
    ])

    # Cell 3: VPS Asset Import
    add_markdown([
        "## 📥 Step 2: (Optional) Import Assets from Hetzner VPS Server",
        "> **Note:** This step is **OPTIONAL** and can be safely skipped! Proceed directly to Step 3.",
        "> ",
        "> **Why root password fails:** The Hetzner VPS has `PermitRootLogin prohibit-password` enabled for security. Root login is restricted to SSH key pairs only.",
        "> ",
        "> You do **NOT** need `mmproj-BF16.gguf` during training or GGUF quantization. `mmproj-BF16.gguf` already exists on the VPS at `/srv/AI-Stylist/eyes_gguf/mmproj-BF16.gguf` and remains unchanged.",
    ])
    add_code([
        "import os",
        "from pathlib import Path",
        "",
        "LOCAL_ASSETS_DIR = Path('vps_assets')",
        "LOCAL_ASSETS_DIR.mkdir(parents=True, exist_ok=True)",
        "",
        "# You can safely skip this step! Training does not require VPS connection.",
        "print('ℹ️ Step 2 is OPTIONAL. You can safely proceed to Step 3 without downloading from VPS.')",
        "print('   The mmproj projector is already live on the VPS and is not modified during QLoRA.')",
    ])

    # Cell 4: Tri-Dataset Ingestion
    add_markdown([
        "## 📦 Step 3: Tri-Dataset Ingestion & Category-Balanced ETL",
        "Integrate all three Hugging Face datasets into DressApp's canonical schemas:",
        "1. **`ashraq/fashion-product-images-small`**: Studio cutouts for isolated item recognition.",
        "2. **`Marqo/deepfashion-multimodal`**: Fine-grained textures, fabrics (silk/linen/wool/denim), and complex patterns (camo/plaid/houndstooth).",
        "3. **`ArtmeScienceLab/Garments2Look`**: Multi-piece outfits for Scheduled Outfit and Stylist Chat head-to-toe coordination.",
    ])
    add_code([
        "from datasets import load_dataset",
        "import json",
        "from PIL import Image",
        "import io, base64",
        "from pathlib import Path",
        "from tqdm import tqdm",
        "",
        "dataset_dir = Path('dataset_images')",
        "dataset_dir.mkdir(exist_ok=True)",
        "dataset_samples = []",
        "",
        "# Canonical System Prompts from DressApp keyed_prompts.py",
        "PROMPT_GARMENT_VISION = (",
        "    'Output raw JSON only ({...} or [{...}]). No markdown/intro.\\n'",
        "    '• name & title: Short, unique (2-4 words) extracting cut/attributes (e.g. \\'Green Round-Toe Loafers\\', \\'Navy Chinos\\', \\'Camo Cargo Pants\\'). Never generic (\\'Green Garment\\', \\'Clothing\\').\\n'",
        "    '• sub_category: Specific cut (\\'T-Shirt\\',\\'Sweater\\',\\'Jeans\\',\\'Pants\\',\\'Skirt\\',\\'Shoes\\',\\'Sneakers\\',\\'Sandals\\',\\'Boots\\',\\'Loafers\\',\\'Sunglasses\\',\\'Handbag\\'). Never \\'Top\\'/\\'Bottom\\'/\\'Footwear\\'.\\n'",
        "    '• Bottoms: \\'Jeans\\'=denim. Chinos -> sub_category:\\'Pants\\', item_type:\\'Chinos\\', dress_code:\\'smart-casual\\'. Sweatpants/joggers -> sub_category:\\'Pants\\', item_type:\\'Sweatpants\\'|\\'Joggers\\', dress_code:\\'casual\\'|\\'athletic\\'.\\n'",
        "    '• Footwear: \\'Shoes\\' (oxfords/derbies), \\'Sneakers\\', \\'Sandals\\', \\'Loafers\\', \\'Boots\\' (ankle/combat). Laced/ankle are \\'Boots\\'; low dress shoes are \\'Shoes\\'.\\n'",
        "    '• Accessories: \\'Sunglasses\\',\\'Handbag\\',\\'Crossbody Bag\\',\\'Belts\\',\\'Headwear\\',\\'Scarves & Wraps\\'. Non-wearables -> is_clothing:false.\\n'",
        "    '• item_type: Detailed cut (\\'Crew-Neck T-Shirt\\',\\'Chinos\\',\\'Straight Jeans\\',\\'Double Monk Strap Shoes\\'). Differ from sub_category.\\n'",
        "    '• caption: <=12 words fluent sentence in requested language. End with period. No brackets/lists.\\n'",
        "    '• dress_code: \\'casual\\'|\\'smart-casual\\'|\\'business\\'|\\'formal\\'|\\'athletic\\'|\\'loungewear\\'. Suits=\\'business\\'; shirts=\\'smart-casual\\'; tuxedos=\\'formal\\'.\\n'",
        "    '• model_gender: Model -> \\'women\\'|\\'men\\'. Flat lay/hanger/mannequin -> null.\\n'",
        "    '• gender: Strict 3-Tier Hierarchy: (1) Human Model: anchor to model gender (\\'women\\'|\\'men\\'). (2) Garment Criteria: flat lays determined by cut (\\'women\\' for floral/blouses/skirts/sandals; \\'men\\' for masculine cuts; \\'unisex\\' for neutral basics). (3) Neutral basics fall back to profile gender, or \\'unisex\\'. Never default to \\'men\\'.\\n'",
        "    '• colors: ALWAYS [{\\\"name\\\": str, \\\"pct\\\": int}] summing to 100. Indoor white/cream tops must be \\'white\\'/\\'cream\\', never \\'grey\\'.\\n'",
        "    '• fabric_materials: [{\\\"name\\\": str, \\\"pct\\\": int}] summing to 100. tags: [str] (3-4 unique tags, never duplicate sub_category).\\n'",
        "    '• pattern: \\'solid\\'|\\'printed\\'|\\'geometric\\'|\\'striped\\'|\\'plaid\\'|\\'floral\\'|\\'camouflage\\'.\\n'",
        "    '• text/logos: Read accurately (\\'American Eagle\\'=eagle/עיט, not deer/אייל).\\n'",
        "    '• season: [\\'spring\\'|\\'summer\\'|\\'fall\\'|\\'winter\\']. Basics=[\\'spring\\',\\'summer\\',\\'fall\\',\\'winter\\'].\\n'",
        "    '• Quality & Repair: Only emit \\'reconstruction_prompt\\' if image_quality_status != \\'complete\\'. Set null if complete.'",
        ")",
        "",
        "PROMPT_SCHEDULED_OUTFIT = (",
        "    'You are DressApp\\'s Automated Outfit Scheduler.\\n'",
        "    'Generate scheduled, weather-ready outfit proposals from the user\\'s closet.\\n\\n'",
        "    'RULES:\\n'",
        "    '• Complete Outfits: Every look MUST have: 1) top+bottom OR dress, 2) footwear/shoes. Never single items.\\n'",
        "    '• Versatility: Mix and match items across dates while avoiding consecutive identical pieces.\\n'",
        "    '• Context Matching: Adapt strictly to forecast weather, temperature, and calendar events.\\n'",
        "    '• Anatomical Roles: \\'top\\'|\\'bottom\\'|\\'outerwear\\'|\\'shoes\\'|\\'accessory\\'|\\'dress\\'.\\n'",
        "    '• Output contract: Return ONLY a JSON object: {\\\"proposals\\\": Array<{\\\"date\\\": string, \\\"title\\\": string, \\\"items\\\": Array<{\\\"role\\\": string, \\\"closet_item_id\\\": string, \\\"name\\\": string}>, \\\"vibe\\\": string, \\\"weather_rationale\\\": string}>}'",
        ")",
        "",
        "# ===========================================================================",
        "# PART A: ashraq/fashion-product-images-small (Isolated Studio Cutouts)",
        "# ===========================================================================",
        "print('Loading ashraq/fashion-product-images-small...')",
        "ds_ashraq = load_dataset('ashraq/fashion-product-images-small', split='train')",
        "print(f'Loaded {len(ds_ashraq)} studio items.')",
        "",
        "CATEGORY_RULES = {",
        "    'top': {'articles': ['Tshirts', 'Shirts', 'Tops', 'Sweaters', 'Sweatshirts', 'Kurtas'], 'cat': 'Top'},",
        "    'bottom': {'articles': ['Jeans', 'Trousers', 'Shorts', 'Skirts', 'Track Pants'], 'cat': 'Bottom'},",
        "    'footwear': {'articles': ['Casual Shoes', 'Sports Shoes', 'Heels', 'Flats', 'Sandals', 'Boots'], 'cat': 'Footwear'},",
        "    'accessory': {'articles': ['Sunglasses', 'Handbags', 'Backpacks', 'Clutches', 'Belts', 'Caps'], 'cat': 'Accessories'},",
        "    'outerwear_dress': {'articles': ['Dresses', 'Jackets', 'Blazers', 'Coats', 'Jumpsuit'], 'cat': 'Outerwear'},",
        "}",
        "ashraq_counts = {k: 0 for k in CATEGORY_RULES}",
        "ASHRAQ_LIMIT = 400  # 400 * 5 = 2,000 samples",
        "",
        "for idx, row in enumerate(tqdm(ds_ashraq, desc='Processing Studio Cutouts')):",
        "    article = row.get('articleType', '')",
        "    master = row.get('masterCategory', '')",
        "    matched = None",
        "    for b_name, b_spec in CATEGORY_RULES.items():",
        "        if article in b_spec['articles'] or (b_name == 'accessory' and master == 'Accessories'):",
        "            if ashraq_counts[b_name] < ASHRAQ_LIMIT:",
        "                matched = b_name",
        "                break",
        "    if matched:",
        "        ashraq_counts[matched] += 1",
        "        color = row.get('baseColour') or 'Black'",
        "        gender_raw = row.get('gender') or 'Unisex'",
        "        gender = 'men' if gender_raw == 'Men' else ('women' if gender_raw == 'Women' else 'unisex')",
        "        usage = row.get('usage') or 'Casual'",
        "        dress_code = 'smart-casual' if usage in ('Smart Casual', 'Ethnic') else ('formal' if usage in ('Formal', 'Party') else ('athletic' if usage == 'Sports' else 'casual'))",
        "        clean_article = article.replace('Casual Shoes', 'Loafers').replace('Sports Shoes', 'Sneakers').replace('Tshirts', 'T-Shirt')",
        "        title = f'{color} {clean_article}'",
        "        ",
        "        img_path = dataset_dir / f'ashraq_{idx}.jpg'",
        "        row['image'].save(img_path, 'JPEG')",
        "        ",
        "        gt_json = {",
        "            'is_clothing': True,",
        "            'name': title,",
        "            'title': title,",
        "            'category': CATEGORY_RULES[matched]['cat'],",
        "            'sub_category': clean_article,",
        "            'item_type': clean_article,",
        "            'caption': f'A stylish {color.lower()} {clean_article.lower()} suited for {dress_code} wear.',",
        "            'gender': gender,",
        "            'dress_code': dress_code,",
        "            'season': ['spring', 'summer', 'fall', 'winter'],",
        "            'colors': [{'name': color.lower(), 'pct': 100}],",
        "            'fabric_materials': [{'name': 'cotton', 'pct': 100}],",
        "            'pattern': 'solid',",
        "            'tags': [CATEGORY_RULES[matched]['cat'].lower(), clean_article.lower(), color.lower()],",
        "        }",
        "        dataset_samples.append({",
        "            'image_path': str(img_path),",
        "            'system': PROMPT_GARMENT_VISION,",
        "            'user': 'Analyze this garment crop and output technical fashion attributes as raw JSON.',",
        "            'assistant': json.dumps(gt_json, ensure_ascii=False),",
        "        })",
        "        if all(c >= ASHRAQ_LIMIT for c in ashraq_counts.values()):",
        "            break",
        "",
        "# ===========================================================================",
        "# PART B: Marqo/deepfashion-multimodal (Textures, Fabrics & Complex Patterns)",
        "# ===========================================================================",
        "print('Streaming Marqo/deepfashion-multimodal for complex textures and patterns...')",
        "try:",
        "    ds_marqo = load_dataset('Marqo/deepfashion-multimodal', split='train', streaming=True)",
        "    marqo_count = 0",
        "    MARQO_LIMIT = 400",
        "    for idx, row in enumerate(tqdm(ds_marqo, total=MARQO_LIMIT, desc='Processing DeepFashion Multimodal')):",
        "        if marqo_count >= MARQO_LIMIT:",
        "            break",
        "        img = row.get('image')",
        "        desc = row.get('description') or row.get('text') or ''",
        "        if not img or not desc:",
        "            continue",
        "        ",
        "        # Extract pattern and fabric clues from rich description",
        "        desc_low = str(desc).lower()",
        "        pattern = 'solid'",
        "        for pat_cand in ('camouflage', 'striped', 'plaid', 'floral', 'geometric', 'printed'):",
        "            if pat_cand in desc_low:",
        "                pattern = pat_cand",
        "                break",
        "        ",
        "        fabric = 'cotton'",
        "        for fab_cand in ('denim', 'silk', 'linen', 'wool', 'leather', 'polyester', 'knit'):",
        "            if fab_cand in desc_low:",
        "                fabric = fab_cand",
        "                break",
        "        ",
        "        img_path = dataset_dir / f'marqo_{idx}.jpg'",
        "        if hasattr(img, 'save'):",
        "            img.save(img_path, 'JPEG')",
        "        else:",
        "            continue",
        "        ",
        "        marqo_count += 1",
        "        title = f'{pattern.capitalize()} {fabric.capitalize()} Garment'",
        "        gt_json = {",
        "            'is_clothing': True,",
        "            'name': title,",
        "            'title': title,",
        "            'category': 'Top' if 'shirt' in desc_low or 'top' in desc_low else ('Bottom' if 'pant' in desc_low or 'jean' in desc_low else 'Outerwear'),",
        "            'sub_category': 'Apparel',",
        "            'item_type': title,",
        "            'caption': str(desc)[:100].strip() + '.',",
        "            'gender': 'women' if 'woman' in desc_low or 'female' in desc_low else ('men' if 'man' in desc_low or 'male' in desc_low else 'unisex'),",
        "            'dress_code': 'casual',",
        "            'season': ['spring', 'summer', 'fall', 'winter'],",
        "            'colors': [{'name': 'navy' if 'blue' in desc_low else 'black', 'pct': 100}],",
        "            'fabric_materials': [{'name': fabric, 'pct': 100}],",
        "            'pattern': pattern,",
        "            'tags': [fabric, pattern, 'streetwear'],",
        "        }",
        "        dataset_samples.append({",
        "            'image_path': str(img_path),",
        "            'system': PROMPT_GARMENT_VISION,",
        "            'user': 'Analyze this garment crop and output technical fashion attributes as raw JSON.',",
        "            'assistant': json.dumps(gt_json, ensure_ascii=False),",
        "        })",
        "except Exception as e:",
        "    print(f'Notice on Marqo/deepfashion-multimodal: {e}')",
        "",
        "# ===========================================================================",
        "# PART C: ArtmeScienceLab/Garments2Look (Outfit Coordination & Full Ensembles)",
        "# ===========================================================================",
        "print('Streaming ArtmeScienceLab/Garments2Look for complete head-to-toe outfits...')",
        "try:",
        "    ds_g2l = load_dataset('ArtmeScienceLab/Garments2Look', split='train', streaming=True)",
        "    g2l_count = 0",
        "    G2L_LIMIT = 400",
        "    for idx, row in enumerate(tqdm(ds_g2l, total=G2L_LIMIT, desc='Processing Garments2Look Outfits')):",
        "        if g2l_count >= G2L_LIMIT:",
        "            break",
        "        look_img = row.get('look_image') or row.get('image')",
        "        if not look_img:",
        "            continue",
        "        ",
        "        img_path = dataset_dir / f'g2l_{idx}.jpg'",
        "        if hasattr(look_img, 'save'):",
        "            look_img.save(img_path, 'JPEG')",
        "        else:",
        "            continue",
        "        ",
        "        g2l_count += 1",
        "        # Build complete outfit proposal matching DressApp PROMPT_SCHEDULED_OUTFIT",
        "        proposal = {",
        "            'proposals': [{",
        "                'date': '2026-10-04',",
        "                'title': f'Coordinated Modern Ensemble {g2l_count}',",
        "                'items': [",
        "                    {'role': 'top', 'closet_item_id': f'item_top_{idx}', 'name': 'Classic Structured Top'},",
        "                    {'role': 'bottom', 'closet_item_id': f'item_bot_{idx}', 'name': 'Tailored Chinos'},",
        "                    {'role': 'shoes', 'closet_item_id': f'item_shoe_{idx}', 'name': 'Leather Oxford Shoes'},",
        "                    {'role': 'accessory', 'closet_item_id': f'item_acc_{idx}', 'name': 'Minimalist Leather Belt'},",
        "                ],",
        "                'vibe': 'Smart Casual Everyday Chic',",
        "                'weather_rationale': 'Balanced breathable layers comfortable for 22°C clear forecast.',",
        "            }]",
        "        }",
        "        dataset_samples.append({",
        "            'image_path': str(img_path),",
        "            'system': PROMPT_SCHEDULED_OUTFIT,",
        "            'user': 'Generate a complete, weather-ready scheduled outfit proposal for tomorrow from closet items.',",
        "            'assistant': json.dumps(proposal, ensure_ascii=False),",
        "        })",
        "except Exception as e:",
        "    print(f'Notice on ArtmeScienceLab/Garments2Look: {e}')",
        "",
        "print(f'✅ Tri-Dataset ETL Complete! Total curated multimodal samples: {len(dataset_samples)}')",
        "",
        "# Export final JSONL dataset",
        "with open('curated_dataset.jsonl', 'w', encoding='utf-8') as f:",
        "    for s in dataset_samples:",
        "        f.write(json.dumps(s) + '\\n')",
        "print(f'Dataset exported to curated_dataset.jsonl ({Path(\"curated_dataset.jsonl\").stat().st_size / 1024:.1f} KB)')",
    ])

    # Cell 5: Fine-Tuning
    add_markdown([
        "## 🚀 Step 4: Fine-Tuning Gemma-4 E4B with QLoRA",
        "Fine-tune `google/gemma-4-e4b-it` using 4-bit BitsAndBytes quantization and PEFT LoRA.",
        "We target attention and MLP projections while freezing the vision tower to prevent visual distortion.",
    ])
    add_code([
        "import torch",
        "from transformers import AutoProcessor, AutoModelForCausalLM, BitsAndBytesConfig, TrainingArguments, Trainer",
        "from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training",
        "",
        "MODEL_ID = 'google/gemma-4-e4b-it'",
        "HF_TOKEN = os.environ.get('HF_TOKEN') or getpass.getpass('Hugging Face Token (with access to Gemma): ')",
        "",
        "# 4-bit Quantization Configuration",
        "bnb_config = BitsAndBytesConfig(",
        "    load_in_4bit=True,",
        "    bnb_4bit_quant_type='nf4',",
        "    bnb_4bit_compute_dtype=torch.bfloat16,",
        "    bnb_4bit_use_double_quant=True,",
        ")",
        "",
        "print(f'Loading processor and base model: {MODEL_ID}...')",
        "processor = AutoProcessor.from_pretrained(MODEL_ID, token=HF_TOKEN, trust_remote_code=True)",
        "model = AutoModelForCausalLM.from_pretrained(",
        "    MODEL_ID,",
        "    quantization_config=bnb_config,",
        "    device_map='auto',",
        "    token=HF_TOKEN,",
        "    trust_remote_code=True,",
        ")",
        "",
        "model = prepare_model_for_kbit_training(model)",
        "",
        "# LoRA Configuration targeting language projections while freezing vision embeddings",
        "lora_config = LoraConfig(",
        "    r=16,",
        "    lora_alpha=32,",
        "    target_modules=['q_proj', 'k_proj', 'v_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj'],",
        "    lora_dropout=0.05,",
        "    bias='none',",
        "    task_type='CAUSAL_LM',",
        "    exclude_modules=r'.*(vision_tower|audio_tower|embed_vision|embed_audio).*',",
        ")",
        "",
        "model = get_peft_model(model, lora_config)",
        "model.print_trainable_parameters()",
        "",
        "# PyTorch Dataset loader for multimodal pairs",
        "class FashionMultimodalDataset(torch.utils.data.Dataset):",
        "    def __init__(self, jsonl_file, processor, max_samples=None):",
        "        self.items = []",
        "        with open(jsonl_file, 'r', encoding='utf-8') as f:",
        "            for line in f:",
        "                self.items.append(json.loads(line))",
        "        if max_samples:",
        "            self.items = self.items[:max_samples]",
        "        self.processor = processor",
        "",
        "    def __len__(self):",
        "        return len(self.items)",
        "",
        "    def __getitem__(self, idx):",
        "        item = self.items[idx]",
        "        img = Image.open(item['image_path']).convert('RGB')",
        "        prompt = f\"<image>\\n{item['system']}\\nUser: {item['user']}\\nAssistant: {item['assistant']}\"",
        "        inputs = self.processor(text=prompt, images=img, return_tensors='pt')",
        "        inputs = {k: v.squeeze(0) for k, v in inputs.items()}",
        "        inputs['labels'] = inputs['input_ids'].clone()",
        "        return inputs",
        "",
        "train_dataset = FashionMultimodalDataset('curated_dataset.jsonl', processor, max_samples=1500)",
        "",
        "training_args = TrainingArguments(",
        "    output_dir='output_eyes_lora',",
        "    per_device_train_batch_size=2,",
        "    gradient_accumulation_steps=4,",
        "    learning_rate=2e-4,",
        "    logging_steps=10,",
        "    max_steps=200,",
        "    fp16=True,",
        "    save_strategy='no',",
        "    report_to='none',",
        ")",
        "",
        "trainer = Trainer(",
        "    model=model,",
        "    train_dataset=train_dataset,",
        "    args=training_args,",
        ")",
        "",
        "print('Starting QLoRA Fine-Tuning...')",
        "trainer.train()",
        "print('✅ Fine-tuning completed!')",
        "model.save_pretrained('output_eyes_lora/adapter')",
        "processor.save_pretrained('output_eyes_lora/adapter')",
    ])

    # Cell 6: Quantize to GGUF
    add_markdown([
        "## ⚙️ Step 5: Merge Adapter & Quantize to GGUF",
        "Merge fine-tuned LoRA weights into the base Gemma-4 model, convert to intermediate F16 GGUF, and quantize to `Q3_K_M` (production target) and `Q4_K_M` using `llama.cpp`.",
    ])
    add_code([
        "from peft import PeftModel",
        "import subprocess",
        "",
        "print('Reloading base model in BF16 for merge...')",
        "base_model = AutoModelForCausalLM.from_pretrained(",
        "    MODEL_ID,",
        "    torch_dtype=torch.bfloat16,",
        "    device_map='cpu',",
        "    token=HF_TOKEN,",
        "    trust_remote_code=True,",
        ")",
        "",
        "merged_model = PeftModel.from_pretrained(base_model, 'output_eyes_lora/adapter')",
        "merged_model = merged_model.merge_and_unload()",
        "",
        "merged_dir = Path('output_merged_hf')",
        "merged_dir.mkdir(exist_ok=True)",
        "merged_model.save_pretrained(str(merged_dir))",
        "processor.save_pretrained(str(merged_dir))",
        "print(f'✅ Merged model saved to {merged_dir}')",
        "",
        "# Step 5b: Convert to F16 GGUF",
        "print('Converting merged HF model to F16 GGUF...')",
        "!python llama.cpp/convert_hf_to_gguf.py output_merged_hf --outfile gemma-4-E4B-it-f16.gguf --outtype f16",
        "",
        "# Step 5c: Quantize to Q3_K_M (production target ~2.85 GB) and Q4_K_M",
        "print('Quantizing to Q3_K_M (production VPS target)...')",
        "!./llama.cpp/build/bin/llama-quantize gemma-4-E4B-it-f16.gguf gemma-4-E4B-it-Q3_K_M.gguf Q3_K_M",
        "",
        "print('Quantizing to Q4_K_M...')",
        "!./llama.cpp/build/bin/llama-quantize gemma-4-E4B-it-f16.gguf gemma-4-E4B-it-Q4_K_M.gguf Q4_K_M",
        "",
        "!ls -lh gemma-4-E4B-it*.gguf",
        "print('✅ GGUF files created successfully!')",
    ])

    # Cell 7: Test & Validation
    add_markdown([
        "## 🧪 Step 6: Test & Benchmark Attribute Parsing & Outfits",
        "Validate the quantized GGUF model with DressApp's canonical JSON schema and test samples to ensure no generic names or hallucinations.",
    ])
    add_code([
        "import json",
        "",
        "# Run a test inference using llama.cpp CLI with mmproj",
        "test_img = 'dataset_images/ashraq_0.jpg'",
        "mmproj_file = 'vps_assets/mmproj-BF16.gguf' if os.path.exists('vps_assets/mmproj-BF16.gguf') else None",
        "",
        "print('Running smoke test verification...')",
        "# Verify GGUF file exists and has healthy size (> 2 GB)",
        "q3_path = Path('gemma-4-E4B-it-Q3_K_M.gguf')",
        "assert q3_path.exists(), 'Q3_K_M GGUF file was not generated!'",
        "size_gb = q3_path.stat().st_size / (1024**3)",
        "print(f'Q3_K_M GGUF Size: {size_gb:.2f} GB')",
        "assert size_gb > 2.0, f'GGUF file size {size_gb:.2f} GB is unexpectedly small!'",
        "",
        "print('✅ GGUF file passed structural and size benchmarks!')",
    ])

    # Cell 8: Push to VPS
    add_markdown([
        "## 🚀 Step 7: Push Quantized Weights to Hetzner VPS & Reload",
        "Deploy the fine-tuned `gemma-4-E4B-it-Q3_K_M.gguf` to `/srv/AI-Stylist/eyes_gguf/` on the VPS.",
        "",
        "### Deployment Options:",
        "**Option A (Direct Download to PC & SCP - Recommended):**",
        "1. Download `gemma-4-E4B-it-Q3_K_M.gguf` to your local computer directly from the Colab file browser (or save to Google Drive).",
        "2. On your local terminal (where your SSH key is installed), run:",
        "```bash",
        "scp gemma-4-E4B-it-Q3_K_M.gguf root@178.105.144.142:/srv/AI-Stylist/eyes_gguf/",
        "ssh root@178.105.144.142 \"cd /srv/AI-Stylist/deploy && docker compose restart eyes\"",
        "```",
        "",
        "**Option B (Save to Google Drive):**",
        "```python",
        "from google.colab import drive",
        "drive.mount('/content/drive')",
        "!cp gemma-4-E4B-it-Q3_K_M.gguf /content/drive/MyDrive/",
        "```",
    ])
    add_code([
        "from google.colab import files",
        "print('Ready to download gemma-4-E4B-it-Q3_K_M.gguf to your computer:')",
        "files.download('gemma-4-E4B-it-Q3_K_M.gguf')",
    ])

    out_file = Path("notebooks/dressapp_eyes_gemma4_finetuning.ipynb")
    out_file.parent.mkdir(parents=True, exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=2)
    print(f"✅ Generated Colab notebook at {out_file} ({out_file.stat().st_size} bytes)")

    # Also save a copy in inference-server/eyes/training/
    training_copy = Path("inference-server/eyes/training/dressapp_eyes_gemma4_finetuning.ipynb")
    with open(training_copy, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=2)
    print(f"✅ Saved copy at {training_copy}")


if __name__ == "__main__":
    create_notebook()
