import { createSimpleStore } from './createSimpleStore';

export const stylistUIStore = createSimpleStore({
  messages: [],
  sessions: [],
  activeSessionId: null,
  outfits: [],
  notifications: [],
  calendarStartDate: new Date(),
  dragOverDay: null,
  selectedOutfitForDetail: null,
  shareDetailModalOpen: false,
  calendarModalOpen: false,
  schedulingDate: null,
  currentCalendarMonth: new Date(),
  isEditingOutfit: false,
  editOutfitName: '',
  editOutfitDescription: '',
  hasAutoSelected: false,
  eventModalOpen: false,
  eventForm: { title: '', date: '', location: '', notes: '' },
  text: '',
  imageFile: null,
  extraImages: [],
  includeCalendar: false,
  occasion: '',
  calendarConnected: false,
  busy: false,
  recording: false,
  interim: '',
  speakingId: null,
  sidebarOpen: false,
  floaterItemId: null,
});
